# Site settings
title: Página principal
description: Cursos y Seminarios
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: jouninLRMD
user_description: Analista de datos, Automatizador de procesos e Ingeniero Biomédico
email: lrmercadod@gmail.com
github_username:  jouninLRMD

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false


# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

theme: jekyll-theme-cayman